add_newline = false

[directory]
truncation_length = 8
truncation_symbol = "…/"

[sudo]
style = "bold green"
symbol = " "
disabled = false

[character]
success_symbol = "[λ](bold green) "
error_symbol = "[λ](bold red) "
vicmd_symbol = "[λ](bold blue) "

[git_branch]
symbol = " "
disabled = false

[git_commit]
commit_hash_length = 6
disabled = false

[git_state]
disabled = false

[git_status]
disabled = false

[username]
disabled = false
